export const OPENING_SAVE_REQUEST = 'OPENING_SAVE_REQUEST';
export const OPENING_SAVE_SUCCESS = 'OPENING_SAVE_SUCCESS';
export const OPENING_SAVE_FAIL = 'OPENING_SAVE_FAIL';
export const OPENING_SAVE_RESET = 'OPENING_SAVE_RESET';
