export const OPENING_LIST_REQUEST = 'OPENING_LIST_REQUEST';
export const OPENING_LIST_SUCCESS = 'OPENING_LIST_SUCCESS';
export const OPENING_LIST_FAIL = 'OPENING_LIST_FAIL';

export const OPENING_DELETE_REQUEST = 'OPENING_DELETE_REQUEST';
export const OPENING_DELETE_SUCCESS = 'OPENING_DELETE_SUCCESS';
export const OPENING_DELETE_FAIL = 'OPENING_DELETE_FAIL';